import { randomUUID } from "node:crypto";
import type { PrismaClient } from "../../lib/db/generated/client";
import type { ApiResult } from "../../contracts/common";
import { failure, success } from "../../lib/api/result";
export type InventoryActor = Readonly<{ adminId: string; permissions: readonly string[] }>;
export type InventoryBalance = Readonly<{ variantId: string; onHand: number; reserved: number; available: number; lowStock: boolean }>;
function id(value: string): boolean { return /^[0-9a-f-]{10,64}$/i.test(value); }
function admin(actor: InventoryActor): boolean { return id(actor.adminId) && actor.permissions.includes("inventory:manage"); }
export class InventoryService {
  constructor(private readonly db: PrismaClient, private readonly now: () => Date = () => new Date()) {}
  async get(variantId: string): Promise<ApiResult<InventoryBalance>> { if (!id(variantId)) return failure("VALIDATION_ERROR"); const balance = await this.db.inventoryBalance.findUnique({ where: { variantId } }); if (!balance) return failure("NOT_FOUND"); return success({ variantId, onHand: balance.onHand, reserved: balance.reserved, available: balance.onHand - balance.reserved, lowStock: balance.onHand - balance.reserved <= balance.lowStockThreshold }); }
  async reserve(orderId: string, variantId: string, quantity: number, expiresAt: Date): Promise<ApiResult<{ reservationId: string }>> { if (!id(orderId) || !id(variantId) || !Number.isSafeInteger(quantity) || quantity < 1 || expiresAt <= this.now()) return failure("VALIDATION_ERROR"); try { const reservationId = randomUUID(); await this.db.$transaction(async tx => { const rows = await tx.$queryRaw<Array<{ onHand: number; reserved: number }>>`SELECT "onHand", reserved FROM "InventoryBalance" WHERE "variantId" = ${variantId} FOR UPDATE`; const balance = rows[0]; if (!balance || balance.onHand - balance.reserved < quantity) throw new Error("OUT_OF_STOCK"); await tx.inventoryBalance.update({ where: { variantId }, data: { reserved: { increment: quantity } } }); await tx.inventoryReservation.create({ data: { id: reservationId, orderId, variantId, quantity, expiresAt } }); }); return success({ reservationId }); } catch (error) { if (error instanceof Error && error.message === "OUT_OF_STOCK") return failure("CONFLICT"); throw error; } }
  async release(reservationId: string): Promise<ApiResult<null>> { const reservation = await this.db.inventoryReservation.findUnique({ where: { id: reservationId } }); if (!reservation) return failure("NOT_FOUND"); if (reservation.status !== "ACTIVE") return success(null); await this.db.$transaction(async tx => { const changed = await tx.inventoryReservation.updateMany({ where: { id: reservationId, status: "ACTIVE" }, data: { status: "RELEASED" } }); if (changed.count) await tx.inventoryBalance.update({ where: { variantId: reservation.variantId }, data: { reserved: { decrement: reservation.quantity } } }); }); return success(null); }
  async commit(reservationId: string): Promise<ApiResult<null>> { const reservation = await this.db.inventoryReservation.findUnique({ where: { id: reservationId } }); if (!reservation) return failure("NOT_FOUND"); if (reservation.status === "COMMITTED") return success(null); if (reservation.status !== "ACTIVE") return failure("CONFLICT"); await this.db.$transaction(async tx => { const changed = await tx.inventoryReservation.updateMany({ where: { id: reservationId, status: "ACTIVE" }, data: { status: "COMMITTED" } }); if (!changed.count) return; await tx.inventoryBalance.update({ where: { variantId: reservation.variantId }, data: { reserved: { decrement: reservation.quantity }, onHand: { decrement: reservation.quantity } } }); await tx.inventoryMovement.create({ data: { id: randomUUID(), variantId: reservation.variantId, quantityDelta: -reservation.quantity, reason: "RESERVATION_COMMITTED", reference: `reservation-commit-${reservation.id}` } }); }); return success(null); }
  async releaseBatch(actor: InventoryActor, batchId: string): Promise<ApiResult<null>> { if (!admin(actor)) return failure("FORBIDDEN"); const batch = await this.db.productionBatch.findUnique({ where: { id: batchId } }); if (!batch) return failure("NOT_FOUND"); if (batch.status === "RELEASED") return success(null); await this.db.$transaction(async tx => { const changed = await tx.productionBatch.updateMany({ where: { id: batchId, status: "RECORDED" }, data: { status: "RELEASED", releasedAt: this.now() } }); if (!changed.count) return; await tx.inventoryBalance.update({ where: { variantId: batch.variantId }, data: { onHand: { increment: batch.producedQuantity } } }); await tx.inventoryMovement.create({ data: { id: randomUUID(), variantId: batch.variantId, productionBatchId: batch.id, quantityDelta: batch.producedQuantity, reason: "PRODUCTION_BATCH_RELEASE", reference: `batch-release-${batch.id}` } }); }); return success(null); }
}
