import { NextResponse } from "next/server";
import { readSessionCookie } from "@/lib/auth/http";
import { getIdentityService } from "@/lib/auth/runtime";
import { getOrdersService } from "@/modules/commerce/orders/runtime";
import { ordersApi } from "@/modules/commerce/orders/service";
export const runtime = "nodejs";
export const dynamic = "force-dynamic";
async function principal(request: Request): Promise<string | null> { const value = await getIdentityService().principal(readSessionCookie(request)); return value?.user.role === "CUSTOMER" ? value.user.id : null; }
export async function GET(request: Request, context: { params: Promise<{ operation: string }> }): Promise<Response> { const customerId = await principal(request); if (!customerId) return NextResponse.json({ ok: false, error: { code: "UNAUTHENTICATED", message: "Sign in to continue." } }, { status: 401 }); const operation = (await context.params).operation; const api = ordersApi(getOrdersService(), customerId); const url = new URL(request.url); if (operation === "list") return NextResponse.json(await api.list({ page: Number(url.searchParams.get("page") ?? 1), pageSize: Number(url.searchParams.get("pageSize") ?? 20) })); if (operation === "detail") return NextResponse.json(await api.get({ id: url.searchParams.get("id") ?? "" })); if (operation === "invoice") return NextResponse.json(await api.getInvoice({ orderId: url.searchParams.get("id") ?? "" })); return NextResponse.json({ ok: false, error: { code: "NOT_FOUND", message: "Order operation not found." } }, { status: 404 }); }
export async function POST(request: Request, context: { params: Promise<{ operation: string }> }): Promise<Response> { if (request.headers.get("origin") !== new URL(request.url).origin) return NextResponse.json({ ok: false, error: { code: "FORBIDDEN", message: "A same-origin request is required." } }, { status: 403 }); const customerId = await principal(request); if (!customerId) return NextResponse.json({ ok: false, error: { code: "UNAUTHENTICATED", message: "Sign in to continue." } }, { status: 401 }); if ((await context.params).operation !== "cancel") return NextResponse.json({ ok: false, error: { code: "NOT_FOUND", message: "Order operation not found." } }, { status: 404 }); const input = await request.json() as { orderId?: string; idempotencyKey?: string }; const result = await ordersApi(getOrdersService(), customerId).requestCancellation({ orderId: input.orderId ?? "", idempotencyKey: input.idempotencyKey ?? "" }); return NextResponse.json(result, { status: result.ok ? 200 : 400 }); }
