import { NextResponse } from "next/server";
import { readSessionCookie } from "@/lib/auth/http";
import { getIdentityService } from "@/lib/auth/runtime";
import { getWishlistService } from "@/modules/commerce/wishlist/runtime";
import { wishlistApi } from "@/modules/commerce/wishlist/service";
export const runtime = "nodejs";
export const dynamic = "force-dynamic";
async function body(request: Request): Promise<Record<string, unknown> | null> { try { const value: unknown = await request.json(); return typeof value === "object" && value !== null && !Array.isArray(value) ? value as Record<string, unknown> : null; } catch { return null; } }
function result(value: unknown, status = 200): Response { return NextResponse.json(value, { status, headers: { "cache-control": "no-store" } }); }
export async function GET(request: Request, context: { params: Promise<{ operation: string }> }): Promise<Response> { if ((await context.params).operation !== "get") return result({ ok: false, error: { code: "NOT_FOUND", message: "Wishlist operation not found." } }, 404); const principal = await getIdentityService().principal(readSessionCookie(request)); if (principal?.user.role !== "CUSTOMER") return result({ ok: false, error: { code: "UNAUTHENTICATED", message: "Sign in to continue." } }, 401); return result(await wishlistApi(getWishlistService(), { customerId: principal.user.id }).get()); }
export async function POST(request: Request, context: { params: Promise<{ operation: string }> }): Promise<Response> { if (request.headers.get("origin") !== new URL(request.url).origin) return result({ ok: false, error: { code: "FORBIDDEN", message: "A same-origin request is required." } }, 403); const principal = await getIdentityService().principal(readSessionCookie(request)); if (principal?.user.role !== "CUSTOMER") return result({ ok: false, error: { code: "UNAUTHENTICATED", message: "Sign in to continue." } }, 401); const input = await body(request); if (!input || typeof input.perfumeId !== "string") return result({ ok: false, error: { code: "VALIDATION_ERROR", message: "A perfume id is required." } }, 400); const operation = (await context.params).operation; const api = wishlistApi(getWishlistService(), { customerId: principal.user.id }); const response = operation === "add" ? await api.add({ perfumeId: input.perfumeId }) : operation === "remove" ? await api.remove({ perfumeId: input.perfumeId }) : { ok: false as const, error: { code: "NOT_FOUND" as const, message: "Wishlist operation not found." } }; return result(response, response.ok ? 200 : response.error.code === "NOT_FOUND" ? 404 : 400); }
