import { NextResponse } from "next/server";
import { readSessionCookie } from "@/lib/auth/http";
import { AuthFault } from "@/lib/auth/errors";
import { getIdentityService } from "@/lib/auth/runtime";
import { getAdminCatalogueService } from "@/modules/catalogue/admin-runtime";
import type { PerfumeInput, VariantInput } from "@/contracts/admin";
export const runtime = "nodejs";
export const dynamic = "force-dynamic";
const status = (result: { ok: boolean; error?: { code: string } }): number => result.ok ? 200 : ({ UNAUTHENTICATED: 401, FORBIDDEN: 403, NOT_FOUND: 404, CONFLICT: 409, VALIDATION_ERROR: 400 }[result.error?.code ?? ""] ?? 500);
async function guard(request: Request): Promise<Response | null> { try { await getIdentityService().requirePermission(readSessionCookie(request), "catalogue:manage"); return null; } catch (error) { const fault = error instanceof AuthFault ? error : new AuthFault("TEMPORARILY_UNAVAILABLE", "The account service is temporarily unavailable."); return NextResponse.json({ ok: false, error: { code: fault.code, message: fault.message } }, { status: status({ ok: false, error: fault }) }); } }
async function body(request: Request): Promise<Record<string, unknown>> { if (!request.headers.get("content-type")?.toLowerCase().startsWith("application/json")) throw new AuthFault("VALIDATION_ERROR", "Use a JSON request body."); const value: unknown = await request.json(); return typeof value === "object" && value !== null ? value as Record<string, unknown> : {}; }
export async function GET(request: Request, context: { params: Promise<{ operation: string }> }): Promise<Response> { const denied = await guard(request); if (denied) return denied; const operation = (await context.params).operation; const service = getAdminCatalogueService(); const url = new URL(request.url); const result = operation === "list" ? await service.list({ page: Number(url.searchParams.get("page") ?? 1), pageSize: Number(url.searchParams.get("pageSize") ?? 20) }) : operation === "perfume" ? await service.get(url.searchParams.get("id") ?? "") : { ok: false, error: { code: "NOT_FOUND", message: "Catalogue operation not found." } } as const; return NextResponse.json(result, { status: status(result) }); }
export async function POST(request: Request, context: { params: Promise<{ operation: string }> }): Promise<Response> { if (request.headers.get("origin") !== new URL(request.url).origin) return NextResponse.json({ ok: false, error: { code: "FORBIDDEN", message: "A same-origin request is required." } }, { status: 403 }); const denied = await guard(request); if (denied) return denied; let input: Record<string, unknown>; try { input = await body(request); } catch (error) { const fault = error instanceof AuthFault ? error : new AuthFault("VALIDATION_ERROR", "Use a valid JSON request body."); return NextResponse.json({ ok: false, error: { code: fault.code, message: fault.message } }, { status: status({ ok: false, error: fault }) }); } const service = getAdminCatalogueService(); const operation = (await context.params).operation; const result = operation === "create" ? await service.create(input as unknown as PerfumeInput) : operation === "update" ? await service.update(typeof input.id === "string" ? input.id : "", typeof input.expectedRevision === "string" ? input.expectedRevision : "", input as unknown as PerfumeInput) : operation === "archive" ? await service.archive(typeof input.id === "string" ? input.id : "", typeof input.expectedRevision === "string" ? input.expectedRevision : "") : operation === "variant-create" ? await service.createVariant(typeof input.perfumeId === "string" ? input.perfumeId : "", input as unknown as VariantInput) : operation === "variant-update" ? await service.updateVariant(typeof input.perfumeId === "string" ? input.perfumeId : "", typeof input.variantId === "string" ? input.variantId : "", typeof input.expectedRevision === "string" ? input.expectedRevision : "", input as unknown as VariantInput) : { ok: false, error: { code: "NOT_FOUND", message: "Catalogue operation not found." } } as const; return NextResponse.json(result, { status: status(result) }); }
