import { randomUUID } from "node:crypto";
import type { Prisma, PrismaClient } from "../../../lib/db/generated/client";
import type { OrdersApi, OrderDetail, OrderSummary, Invoice } from "../../../contracts/orders";
import type { ApiResult, PageRequest } from "../../../contracts/common";
import { failure, success } from "../../../lib/api/result";
const include = { items: true, payment: true, invoice: true, shipment: true, deliveryMethod: true } as const;
type Loaded = Prisma.OrderGetPayload<{ include: typeof include }>;
function id(value: string): boolean { return /^[0-9a-f-]{10,64}$/i.test(value); }
function address(value: unknown): { recipientName: string; line1: string; line2: string | null; suburb: string; state: string; postcode: string; country: string } { const input = value as Record<string, unknown>; return { recipientName: String(input.recipientName ?? ""), line1: String(input.line1 ?? ""), line2: typeof input.line2 === "string" ? input.line2 : null, suburb: String(input.suburb ?? ""), state: String(input.state ?? ""), postcode: String(input.postcode ?? ""), country: String(input.country ?? "") }; }
export class OrdersService {
  constructor(private readonly db: PrismaClient, private readonly now: () => Date = () => new Date()) {}
  private summary(order: Loaded): OrderSummary { return { id: order.id, orderNumber: order.orderNumber, placedAt: order.placedAt.toISOString(), status: order.status, paymentStatus: order.payment?.status ?? "PENDING", total: { amountMinor: order.totalMinor, currency: order.currency } }; }
  private detail(order: Loaded): OrderDetail { return { ...this.summary(order), items: order.items.map(item => ({ id: item.id, variantId: item.variantId, sku: item.skuSnapshot, title: item.nameSnapshot, quantity: item.quantity, unitPrice: { amountMinor: item.unitPriceMinor, currency: order.currency }, customisation: { personalisedLabel: item.personalisedLabel, engravingName: item.engravingName, giftMessage: item.giftMessage, giftPackagingId: item.giftPackagingId } })), subtotal: { amountMinor: order.subtotalMinor, currency: order.currency }, discountTotal: { amountMinor: order.discountTotalMinor, currency: order.currency }, deliveryAddress: address(order.deliveryAddressSnapshot), billingAddress: address(order.billingAddressSnapshot), deliveryMethod: { id: order.deliveryMethod.id, name: order.deliveryMethod.name, charge: { amountMinor: order.deliveryMethod.chargeMinor, currency: order.deliveryMethod.currency }, displayInformation: order.deliveryMethod.displayInformation }, invoiceId: order.invoice?.id ?? null, shipmentId: order.shipment?.id ?? null, canRequestCancellation: !["SHIPPED", "DELIVERED"].includes(order.status) && order.status !== "PROCESSING", cancellationRequest: order.cancellationRequestedAt ? { requestedAt: order.cancellationRequestedAt.toISOString() } : null }; }
  private async load(customerId: string, orderId: string): Promise<Loaded | null> { return this.db.order.findFirst({ where: { id: orderId, customerId }, include }); }
  async list(customerId: string, request: PageRequest): Promise<ApiResult<{ items: readonly OrderSummary[]; page: number; pageSize: number; hasMore: boolean }>> { if (!id(customerId)) return failure("UNAUTHENTICATED"); const page = request.page ?? 1; const pageSize = Math.min(request.pageSize ?? 20, 50); if (!Number.isSafeInteger(page) || page < 1) return failure("VALIDATION_ERROR"); const orders = await this.db.order.findMany({ where: { customerId }, include, orderBy: { placedAt: "desc" }, skip: (page - 1) * pageSize, take: pageSize + 1 }); return success({ items: orders.slice(0, pageSize).map(order => this.summary(order)), page, pageSize, hasMore: orders.length > pageSize }); }
  async get(customerId: string, orderId: string): Promise<ApiResult<OrderDetail>> { const order = id(customerId) && id(orderId) ? await this.load(customerId, orderId) : null; return order ? success(this.detail(order)) : failure(id(customerId) ? "NOT_FOUND" : "UNAUTHENTICATED"); }
  async invoice(customerId: string, orderId: string): Promise<ApiResult<Invoice>> { const order = id(customerId) && id(orderId) ? await this.load(customerId, orderId) : null; if (!order) return failure(id(customerId) ? "NOT_FOUND" : "UNAUTHENTICATED"); if (order.payment?.status !== "SUCCEEDED") return failure("CONFLICT"); const invoice = order.invoice ?? await this.db.invoice.create({ data: { id: randomUUID(), orderId: order.id, invoiceNumber: `PAL-INV-${order.orderNumber}`, totalMinor: order.totalMinor, currency: order.currency, paymentReferenceSnapshot: order.payment.providerReference ?? "sandbox" } }); const refreshed = await this.load(customerId, orderId); if (!refreshed) return failure("NOT_FOUND"); return success({ id: invoice.id, invoiceNumber: invoice.invoiceNumber, issuedAt: invoice.issuedAt.toISOString(), order: this.detail(refreshed), paymentReference: invoice.paymentReferenceSnapshot }); }
  async cancel(customerId: string, orderId: string, idempotencyKey: string): Promise<ApiResult<{ requestedAt: string }>> { if (!id(customerId) || !id(orderId) || !/^[A-Za-z0-9_-]{16,128}$/.test(idempotencyKey)) return failure("VALIDATION_ERROR"); const order = await this.load(customerId, orderId); if (!order) return failure("NOT_FOUND"); if (order.cancellationRequestedAt) return success({ requestedAt: order.cancellationRequestedAt.toISOString() }); if (["PROCESSING", "SHIPPED", "DELIVERED"].includes(order.status)) return failure("CONFLICT"); const requestedAt = this.now(); await this.db.order.update({ where: { id: order.id }, data: { cancellationRequestedAt: requestedAt } }); return success({ requestedAt: requestedAt.toISOString() }); }
}
export function ordersApi(service: OrdersService, customerId: string): OrdersApi { return { list: input => service.list(customerId, input), get: input => service.get(customerId, input.id), getInvoice: input => service.invoice(customerId, input.orderId), requestCancellation: input => service.cancel(customerId, input.orderId, input.idempotencyKey) }; }
