"use client";
import * as React from "react";
import { Button } from "@/components/ui/button";
import { ErrorState } from "@/components/ui/error-state";
import type { ParticipationAccount } from "@/contracts/participation";
import { api } from "@/lib/api";
export function CustomerParticipation() {
  const [account, setAccount] = React.useState<ParticipationAccount | null>(null); const [error, setError] = React.useState<string | null>(null); const [busy, setBusy] = React.useState(false); const [code, setCode] = React.useState(""); const [notice, setNotice] = React.useState<string | null>(null);
  const load = React.useCallback(async () => { const result = await api.participation.account(); if (result.ok) { setError(null); setAccount(result.data); } else setError(result.error.message); }, []); React.useEffect(() => { let active = true; void api.participation.account().then(result => { if (!active) return; if (result.ok) { setError(null); setAccount(result.data); } else setError(result.error.message); }); return () => { active = false; }; }, []);
  async function change(op: "subscription" | "code" | "apply") { setBusy(true); setNotice(null); const result = op === "subscription" ? await api.participation.setSubscription({ optedIn: !account?.subscription.optedIn }) : op === "code" ? await api.participation.referralCode() : await api.participation.applyReferral({ code: code.trim().toUpperCase() }); setBusy(false); if (!result.ok) { setNotice(result.error.code === "CONFLICT" ? "A referral has already been applied to this account." : result.error.code === "FORBIDDEN" ? "That referral code cannot be applied to this account." : result.error.message); return; } if (op === "apply") setCode(""); await load(); setNotice("Saved."); }
  return <section className="mt-16 border-t border-border pt-5" aria-labelledby="participation-heading"><p className="text-xs font-medium uppercase tracking-[.14em] text-text-muted">Your participation</p><h2 id="participation-heading" className="mt-2 text-h3 font-normal">Rewards and preferences</h2>{!account && !error && <div aria-busy="true" className="mt-6 h-28 animate-pulse bg-surface-muted" />}{error && <div className="mt-6"><ErrorState title="Could not load participation" message={error} onRetry={() => void load()} /></div>}{account && <div className="mt-6 grid gap-8 lg:grid-cols-3"><section><h3 className="font-medium">Loyalty balance</h3><p className="mt-3 text-3xl font-light">{account.loyalty.points} points</p><p className="mt-3 text-sm text-text-muted">{account.loyalty.entries.length ? `${account.loyalty.entries.length} persisted reward entries.` : "No persisted rewards yet."}</p></section><section><h3 className="font-medium">Subscription</h3><p className="mt-3 text-sm text-text-muted">{account.subscription.optedIn ? "You are opted in to Palermo updates." : "You are currently opted out."}</p><Button className="mt-5" type="button" variant="outline" isLoading={busy} onClick={() => void change("subscription")}>{account.subscription.optedIn ? "Opt out" : "Opt in"}</Button></section><section><h3 className="font-medium">Referral</h3>{account.referral.code ? <p className="mt-3 text-sm">Your code: <strong>{account.referral.code}</strong></p> : <Button className="mt-4" type="button" variant="outline" isLoading={busy} onClick={() => void change("code")}>Create referral code</Button>}<p className="mt-3 text-sm text-text-muted">Share this code directly; referral links are not currently supported.</p>{account.referral.received && <p className="mt-3 text-sm text-text-muted">Applied referral: {account.referral.received.status === "QUALIFIED" ? "qualified" : "awaiting qualification"}.</p>}<form className="mt-5" onSubmit={event => { event.preventDefault(); void change("apply"); }}><label className="block text-sm">Apply a referral code<input required value={code} onChange={event => setCode(event.target.value)} maxLength={24} className="mt-2 min-h-11 w-full border border-border-strong bg-surface px-3" /></label><Button className="mt-3" type="submit" variant="outline" isLoading={busy}>Apply code</Button></form></section></div>}{notice && <p role="status" className="mt-5 text-sm text-text-muted">{notice}</p>}</section>;
}
