"use client";
import * as React from "react";
import { Button } from "@/components/ui/button";
import { ErrorState } from "@/components/ui/error-state";
import type { PublicReview } from "@/contracts/reviews";
import { api } from "@/lib/api";

export function ProductReviews({ perfumeId }: { perfumeId: string }) {
  const [reviews, setReviews] = React.useState<readonly PublicReview[] | null>(null); const [error, setError] = React.useState<string | null>(null); const [rating, setRating] = React.useState(5); const [text, setText] = React.useState(""); const [pending, setPending] = React.useState(false); const [message, setMessage] = React.useState<string | null>(null);
  const load = React.useCallback(async () => { const result = await api.reviews.publicForPerfume({ perfumeId }); if (result.ok) { setError(null); setReviews(result.data); } else setError(result.error.message); }, [perfumeId]);
  React.useEffect(() => { let active = true; void api.reviews.publicForPerfume({ perfumeId }).then(result => { if (!active) return; if (result.ok) { setError(null); setReviews(result.data); } else setError(result.error.message); }); return () => { active = false; }; }, [perfumeId]);
  async function submit(event: React.FormEvent) { event.preventDefault(); setPending(true); setMessage(null); const result = await api.reviews.create({ perfumeId, rating, text: text.trim() }); setPending(false); if (result.ok) { setText(""); setMessage("Your review is pending moderation."); } else setMessage(result.error.code === "FORBIDDEN" ? "A completed paid order for this fragrance is required before you can review it." : result.error.code === "CONFLICT" ? "You already have a review for this fragrance." : result.error.message); }
  return <section className="mt-16 border-t border-border pt-8 sm:mt-20 sm:pt-10" aria-labelledby="reviews-heading"><div className="grid gap-10 lg:grid-cols-[minmax(0,1fr)_22rem]"><div><p className="text-xs font-medium uppercase tracking-[.18em] text-text-muted">Customer reviews</p><h2 id="reviews-heading" className="mt-3 text-[clamp(2.25rem,3.6vw,3.75rem)] font-[300] leading-[.98] tracking-[-.055em]">Notes from the collection</h2>{reviews === null && !error && <div aria-busy="true" className="mt-7 h-24 animate-pulse bg-surface-muted" />}{error && <div className="mt-7"><ErrorState title="Could not load reviews" message={error} onRetry={() => void load()} /></div>}{reviews && (reviews.length ? <ul className="mt-7 border-t border-border">{reviews.map(review => <li key={review.id} className="border-b border-border py-5"><p aria-label={`${review.rating} out of 5 stars`} className="text-sm">{'★'.repeat(review.rating)}{'☆'.repeat(5 - review.rating)}</p><p className="mt-3 text-sm leading-6 text-text-muted">{review.text}</p></li>)}</ul> : <p className="mt-7 text-sm text-text-muted">No approved reviews have been published for this fragrance yet.</p>)}</div><form className="border-t border-border pt-4" onSubmit={event => { void submit(event); }}><h3 className="font-medium">Share your experience</h3><p className="mt-2 text-sm leading-6 text-text-muted">Reviews from completed paid orders are checked before publication.</p><label className="mt-5 block text-sm">Rating<select value={rating} onChange={event => setRating(Number(event.target.value))} className="mt-2 min-h-11 w-full border border-border-strong bg-surface px-3">{[5,4,3,2,1].map(value => <option key={value} value={value}>{value} stars</option>)}</select></label><label className="mt-5 block text-sm">Your review<textarea required maxLength={1000} value={text} onChange={event => setText(event.target.value)} className="mt-2 min-h-28 w-full border border-border-strong bg-surface px-3 py-2" /></label><Button className="mt-5" type="submit" isLoading={pending}>Submit review</Button>{message && <p role="status" className="mt-4 text-sm text-text-muted">{message}</p>}</form></div></section>;
}
