import { randomUUID } from "node:crypto";
import type { Prisma, PrismaClient } from "../../lib/db/generated/client";
import type { AdminPerfume, Dashboard, InventoryBalance, PerfumeInput, ProductionBatch, VariantInput } from "../../contracts/admin";
import type { PerfumeDetail, PerfumeVariantSummary, SuitabilitySummary } from "../../contracts/catalogue";
import type { ApiResult, Option, PageRequest, Page } from "../../contracts/common";
import { failure, success } from "../../lib/api/result";

const id = (value: unknown): value is string => typeof value === "string" && /^[0-9a-f-]{10,64}$/i.test(value);
const text = (value: unknown, max: number): value is string => typeof value === "string" && value.trim().length > 0 && value.length <= max;
const revision = (value: unknown): number | null => typeof value === "string" && /^catalogue-[1-9][0-9]*$/.test(value) ? Number(value.slice(10)) : null;
const option = (value: { id: string; name?: string; value?: string }): Option => ({ id: value.id, label: value.name ?? value.value ?? value.id });
const money = (amountMinor: number, currency: string) => ({ amountMinor, currency });

type Loaded = Prisma.PerfumeGetPayload<{ include: { primaryFamily: true; intensity: true; images: true; variants: true; notes: { include: { note: true } }; suitability: { include: { tag: true } } } }>;
const include = { primaryFamily: true, intensity: true, images: true, variants: true, notes: { include: { note: true } }, suitability: { include: { tag: true } } } as const;

function validInput(input: PerfumeInput): boolean {
  if (!text(input.name, 160) || !/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(input.slug) || !text(input.description, 5000) || !id(input.primaryFamilyId)) return false;
  if (input.intensity !== null && (!id(input.intensity?.id) || !text(input.intensity?.label, 120))) return false;
  if (!Array.isArray(input.notes) || !Array.isArray(input.images)) return false;
  if (!input.suitability || !Object.values(input.suitability).every(value => Array.isArray(value))) return false;
  const notes = input.notes as readonly { id: unknown; label: unknown; layer: string }[];
  const images = input.images as readonly { id: unknown; url: unknown; alt: unknown }[];
  return notes.every(note => id(note.id) && text(note.label, 120) && ["TOP", "MIDDLE", "BASE"].includes(note.layer))
    && images.every(image => id(image.id) && text(image.url, 2048) && text(image.alt, 255));
}
function validVariant(input: VariantInput): boolean {
  return text(input.sku, 80) && text(input.bottleSize, 80) && text(input.concentration, 120)
    && Number.isSafeInteger(input.price.amountMinor) && input.price.amountMinor >= 0
    && /^[A-Z]{3}$/.test(input.price.currency) && ["AVAILABLE", "OUT_OF_STOCK", "UNAVAILABLE"].includes(input.availability)
    && !!input.customisations && typeof input.customisations.personalisedLabel === "boolean"
    && typeof input.customisations.engravingName === "boolean" && typeof input.customisations.giftMessage === "boolean"
    && Array.isArray(input.customisations.giftPackaging) && (input.customisations.giftPackaging as readonly { id: unknown; label: unknown }[]).every(item => id(item.id) && text(item.label, 120));
}
function dto(perfume: Loaded): AdminPerfume {
  const variants: PerfumeVariantSummary[] = perfume.variants.map(variant => ({ id: variant.id, sku: variant.sku, bottleSize: variant.bottleSize, concentration: variant.concentration, price: money(variant.priceMinor, variant.currency), availability: variant.availability, customisations: { personalisedLabel: variant.personalisedLabel, engravingName: variant.engravingName, giftMessage: variant.giftMessage, giftPackaging: Array.isArray(variant.giftPackagingOptions) ? variant.giftPackagingOptions as never : [] } }));
  const grouped: SuitabilitySummary = { occasion: [], mood: [], weather: [], daypart: [], season: [] };
  for (const item of perfume.suitability) (grouped[item.tag.category.toLowerCase() as keyof SuitabilitySummary] as Option[]).push(option(item.tag));
  const detail: PerfumeDetail = { id: perfume.id, slug: perfume.slug, name: perfume.name, description: perfume.description, primaryFamily: option(perfume.primaryFamily), imageUrl: perfume.images[0]?.url ?? null, priceFrom: money(Math.min(...perfume.variants.map(item => item.priceMinor), 0), perfume.variants[0]?.currency ?? "AUD"), intensity: perfume.intensity ? option(perfume.intensity) : null, notes: perfume.notes.map(item => ({ id: item.note.id, label: item.note.name, description: item.note.description, layer: item.layer })), variants, suitability: grouped, images: perfume.images.sort((a, b) => a.sortOrder - b.sortOrder).map(image => ({ id: image.id, url: image.url, alt: image.alt })), longevity: perfume.longevity ? { id: `longevity:${perfume.longevity}`, label: perfume.longevity } : null, projection: perfume.projection ? { id: `projection:${perfume.projection}`, label: perfume.projection } : null };
  return { perfume: detail, status: perfume.status, revision: `catalogue-${perfume.revision}` };
}

export class AdminCatalogueService {
  constructor(private readonly db: PrismaClient, private readonly now: () => Date = () => new Date()) {}
  private async load(idValue: string): Promise<Loaded | null> { return id(idValue) ? this.db.perfume.findUnique({ where: { id: idValue }, include }) : null; }
  private async writeRelations(tx: Prisma.TransactionClient, perfumeId: string, input: PerfumeInput): Promise<void> {
    await tx.perfumeNote.deleteMany({ where: { perfumeId } }); await tx.perfumeSuitability.deleteMany({ where: { perfumeId } }); await tx.perfumeImage.deleteMany({ where: { perfumeId } });
    if (input.notes.length) await tx.perfumeNote.createMany({ data: input.notes.map(note => ({ perfumeId, noteId: note.id, layer: note.layer })) });
    const tags = Object.values(input.suitability).flatMap(values => values.map(value => ({ perfumeId, tagId: value.id })));
    if (tags.length) await tx.perfumeSuitability.createMany({ data: tags });
    if (input.images.length) await tx.perfumeImage.createMany({ data: input.images.map((image, index) => ({ id: image.id, perfumeId, url: image.url, alt: image.alt, sortOrder: index })) });
  }
  async list(request: PageRequest): Promise<ApiResult<Page<AdminPerfume>>> { const page = request.page ?? 1; const pageSize = request.pageSize ?? 20; if (!Number.isSafeInteger(page) || page < 1 || !Number.isSafeInteger(pageSize) || pageSize < 1 || pageSize > 100) return failure("VALIDATION_ERROR"); const [rows, total] = await Promise.all([this.db.perfume.findMany({ include, orderBy: [{ name: "asc" }, { id: "asc" }], skip: (page - 1) * pageSize, take: pageSize }), this.db.perfume.count()]); return success({ items: rows.map(dto), page, pageSize, hasMore: page * pageSize < total }); }
  async get(idValue: string): Promise<ApiResult<AdminPerfume>> { const row = await this.load(idValue); return row ? success(dto(row)) : failure("NOT_FOUND"); }
  async dashboard(period: { from: string; to: string }): Promise<ApiResult<Dashboard>> { const from = new Date(period.from); const to = new Date(period.to); if (!Number.isFinite(from.getTime()) || !Number.isFinite(to.getTime()) || from >= to) return failure("VALIDATION_ERROR"); const [orders, bestSelling, lowStockVariantCount] = await Promise.all([this.db.order.aggregate({ where: { placedAt: { gte: from, lt: to }, payment: { status: "SUCCEEDED" } }, _sum: { totalMinor: true }, _count: { _all: true } }), this.db.orderItem.groupBy({ by: ["variantId"], where: { order: { placedAt: { gte: from, lt: to }, payment: { status: "SUCCEEDED" } } }, _sum: { quantity: true }, orderBy: { _sum: { quantity: "desc" } }, take: 5 }), this.db.inventoryBalance.count({ where: { onHand: { lte: 3 } } })]); const products = await this.db.perfume.findMany({ where: { variants: { some: { id: { in: bestSelling.map(item => item.variantId) } } } }, select: { id: true, name: true, variants: { where: { id: { in: bestSelling.map(item => item.variantId) } }, select: { id: true } } } }); return success({ period, totalSales: money(orders._sum.totalMinor ?? 0, "AUD"), totalOrders: orders._count._all, bestSelling: bestSelling.flatMap(item => { const product = products.find(value => value.variants.some(variant => variant.id === item.variantId)); return product ? [{ perfumeId: product.id, name: product.name, unitsSold: item._sum.quantity ?? 0 }] : []; }), lowStockVariantCount }); }
  async inventory(request: PageRequest): Promise<ApiResult<Page<InventoryBalance>>> { const page = request.page ?? 1; const pageSize = request.pageSize ?? 20; if (!Number.isSafeInteger(page) || page < 1 || !Number.isSafeInteger(pageSize) || pageSize < 1 || pageSize > 100) return failure("VALIDATION_ERROR"); const [rows, total] = await Promise.all([this.db.inventoryBalance.findMany({ include: { variant: true }, orderBy: { variantId: "asc" }, skip: (page - 1) * pageSize, take: pageSize }), this.db.inventoryBalance.count()]); return success({ items: rows.map(row => ({ variantId: row.variantId, sku: row.variant.sku, onHand: row.onHand, reserved: row.reserved, available: row.onHand - row.reserved, lowStockThreshold: row.lowStockThreshold, lowStock: row.onHand - row.reserved <= row.lowStockThreshold, updatedAt: row.updatedAt.toISOString() })), page, pageSize, hasMore: page * pageSize < total }); }
  async batches(request: PageRequest): Promise<ApiResult<Page<ProductionBatch>>> { const page = request.page ?? 1; const pageSize = request.pageSize ?? 20; if (!Number.isSafeInteger(page) || page < 1 || !Number.isSafeInteger(pageSize) || pageSize < 1 || pageSize > 100) return failure("VALIDATION_ERROR"); const [rows, total] = await Promise.all([this.db.productionBatch.findMany({ orderBy: { productionDate: "desc" }, skip: (page - 1) * pageSize, take: pageSize }), this.db.productionBatch.count()]); return success({ items: rows.map(row => ({ id: row.id, variantId: row.variantId, batchCode: row.batchCode, producedQuantity: row.producedQuantity, status: row.status, productionDate: row.productionDate.toISOString(), releasedAt: row.releasedAt?.toISOString() ?? null })), page, pageSize, hasMore: page * pageSize < total }); }
  async create(input: PerfumeInput & { idempotencyKey?: string }): Promise<ApiResult<AdminPerfume>> { if (!validInput(input) || !text(input.idempotencyKey, 128)) return failure("VALIDATION_ERROR"); try { const row = await this.db.$transaction(async tx => { const created = await tx.perfume.create({ data: { id: randomUUID(), slug: input.slug, name: input.name.trim(), description: input.description.trim(), primaryFamilyId: input.primaryFamilyId, intensityId: input.intensity?.id ?? null, longevity: input.longevity?.label ?? null, projection: input.projection?.label ?? null }, include }); await this.writeRelations(tx, created.id, input); return tx.perfume.findUniqueOrThrow({ where: { id: created.id }, include }); }); return success(dto(row)); } catch { return failure("VALIDATION_ERROR"); } }
  async update(idValue: string, expected: string, input: PerfumeInput): Promise<ApiResult<AdminPerfume>> { const expectedNumber = revision(expected); if (!id(idValue) || expectedNumber === null || !validInput(input)) return failure("VALIDATION_ERROR"); const current = await this.load(idValue); if (!current) return failure("NOT_FOUND"); if (current.status !== "ACTIVE" || current.revision !== expectedNumber) return failure("CONFLICT"); const row = await this.db.$transaction(async tx => { const updated = await tx.perfume.updateMany({ where: { id: idValue, status: "ACTIVE", revision: expectedNumber }, data: { slug: input.slug, name: input.name.trim(), description: input.description.trim(), primaryFamilyId: input.primaryFamilyId, intensityId: input.intensity?.id ?? null, longevity: input.longevity?.label ?? null, projection: input.projection?.label ?? null, revision: { increment: 1 } } }); if (updated.count !== 1) return null; await this.writeRelations(tx, idValue, input); return tx.perfume.findUniqueOrThrow({ where: { id: idValue }, include }); }); return row ? success(dto(row)) : failure("CONFLICT"); }
  async archive(idValue: string, expected: string): Promise<ApiResult<AdminPerfume>> { const expectedNumber = revision(expected); if (!id(idValue) || expectedNumber === null) return failure("VALIDATION_ERROR"); const updated = await this.db.perfume.updateMany({ where: { id: idValue, status: "ACTIVE", revision: expectedNumber }, data: { status: "ARCHIVED", archivedAt: this.now(), revision: { increment: 1 } } }); if (updated.count !== 1) { const exists = await this.load(idValue); return exists ? failure("CONFLICT") : failure("NOT_FOUND"); } const row = await this.load(idValue); return row ? success(dto(row)) : failure("NOT_FOUND"); }
  async createVariant(perfumeId: string, input: VariantInput & { idempotencyKey?: string }): Promise<ApiResult<PerfumeVariantSummary>> { if (!id(perfumeId) || !validVariant(input) || !text(input.idempotencyKey, 128)) return failure("VALIDATION_ERROR"); const perfume = await this.load(perfumeId); if (!perfume) return failure("NOT_FOUND"); if (perfume.status !== "ACTIVE") return failure("CONFLICT"); try { const variant = await this.db.perfumeVariant.create({ data: { id: randomUUID(), perfumeId, sku: input.sku.trim(), bottleSize: input.bottleSize.trim(), concentration: input.concentration.trim(), priceMinor: input.price.amountMinor, currency: input.price.currency, availability: input.availability, personalisedLabel: input.customisations.personalisedLabel, engravingName: input.customisations.engravingName, giftMessage: input.customisations.giftMessage, giftPackagingOptions: input.customisations.giftPackaging }, }); await this.db.perfume.update({ where: { id: perfumeId }, data: { revision: { increment: 1 } } }); return success({ id: variant.id, sku: variant.sku, bottleSize: variant.bottleSize, concentration: variant.concentration, price: money(variant.priceMinor, variant.currency), availability: variant.availability, customisations: { personalisedLabel: variant.personalisedLabel, engravingName: variant.engravingName, giftMessage: variant.giftMessage, giftPackaging: input.customisations.giftPackaging } }); } catch { return failure("VALIDATION_ERROR"); } }
  async updateVariant(perfumeId: string, variantId: string, expected: string, input: VariantInput): Promise<ApiResult<PerfumeVariantSummary>> { const expectedNumber = revision(expected); if (!id(perfumeId) || !id(variantId) || expectedNumber === null || !validVariant(input)) return failure("VALIDATION_ERROR"); const variant = await this.db.perfumeVariant.findFirst({ where: { id: variantId, perfumeId }, include: { perfume: true } }); if (!variant) return failure("NOT_FOUND"); if (variant.perfume.status !== "ACTIVE" || variant.perfume.revision !== expectedNumber) return failure("CONFLICT"); const result = await this.db.$transaction(async tx => { const changed = await tx.perfume.updateMany({ where: { id: perfumeId, status: "ACTIVE", revision: expectedNumber }, data: { revision: { increment: 1 } } }); if (changed.count !== 1) return null; return tx.perfumeVariant.update({ where: { id: variantId }, data: { sku: input.sku.trim(), bottleSize: input.bottleSize.trim(), concentration: input.concentration.trim(), priceMinor: input.price.amountMinor, currency: input.price.currency, availability: input.availability, personalisedLabel: input.customisations.personalisedLabel, engravingName: input.customisations.engravingName, giftMessage: input.customisations.giftMessage, giftPackagingOptions: input.customisations.giftPackaging } }); }); if (!result) return failure("CONFLICT"); return success({ id: result.id, sku: result.sku, bottleSize: result.bottleSize, concentration: result.concentration, price: money(result.priceMinor, result.currency), availability: result.availability, customisations: { personalisedLabel: result.personalisedLabel, engravingName: result.engravingName, giftMessage: result.giftMessage, giftPackaging: input.customisations.giftPackaging } }); }
}
