import { createHash, randomUUID } from "node:crypto";
import type { Prisma, PrismaClient } from "../../../lib/db/generated/client";
import type { CheckoutApi, CheckoutRequest, CheckoutResult, DeliveryMethod } from "../../../contracts/checkout";
import type { ApiResult } from "../../../contracts/common";
import { failure, success } from "../../../lib/api/result";

const include = { items: { include: { variant: { include: { perfume: true, inventory: true } } } }, promotion: true } as const;
type Cart = Prisma.CartGetPayload<{ include: typeof include }>;
function id(value: string): boolean { return /^[0-9a-f-]{10,64}$/i.test(value); }
function fingerprint(input: CheckoutRequest): string { return createHash("sha256").update(JSON.stringify(input)).digest("hex"); }
function money(cart: Cart): { subtotal: number; discount: number; total: number } { const subtotal = cart.items.reduce((sum, item) => sum + item.variant.priceMinor * item.quantity, 0); const promotion = cart.promotion; const discount = promotion?.active ? promotion.discountType === "FIXED" ? Math.min(subtotal, promotion.discountValue) : Math.min(subtotal, Math.floor(subtotal * promotion.discountValue / 10000)) : 0; return { subtotal, discount, total: subtotal - discount }; }
export class CheckoutService {
  constructor(private readonly db: PrismaClient, private readonly now: () => Date = () => new Date()) {}
  async getDeliveryMethods(): Promise<ApiResult<readonly DeliveryMethod[]>> { const methods = await this.db.deliveryMethod.findMany({ where: { active: true }, orderBy: { chargeMinor: "asc" } }); return success(methods.map(method => ({ id: method.id, name: method.name, charge: { amountMinor: method.chargeMinor, currency: method.currency }, displayInformation: method.displayInformation }))); }
  async submit(customerId: string, input: CheckoutRequest): Promise<ApiResult<CheckoutResult>> {
    if (!id(customerId) || !id(input.cartId) || !id(input.deliveryAddressId) || !id(input.billingAddressId) || !id(input.deliveryMethodId) || !/^[A-Za-z0-9_-]{16,128}$/.test(input.idempotencyKey)) return failure("VALIDATION_ERROR");
    const existing = await this.db.order.findUnique({ where: { customerId_idempotencyKey: { customerId, idempotencyKey: input.idempotencyKey } }, include: { payment: true } });
    if (existing) { if (existing.requestFingerprint !== fingerprint(input)) return success({ status: "CHECKOUT_CONFLICT", message: "The idempotency key was already used for different checkout details." }); return success({ status: "READY_FOR_PAYMENT", orderId: existing.id, paymentAttemptId: existing.payment?.id ?? existing.id, expiresAt: new Date(this.now().getTime() + 15 * 60 * 1000).toISOString() }); }
    const cart = await this.db.cart.findFirst({ where: { id: input.cartId, customerId, status: "ACTIVE" }, include }); if (!cart || `cart-${cart.revision}` !== input.expectedCartRevision || !cart.items.length) return success({ status: "REQUIRES_CART_REVIEW", cart: { id: input.cartId, revision: `cart-${cart?.revision ?? 0}`, kind: "CUSTOMER", items: [], pricing: { subtotal: { amountMinor: 0, currency: "AUD" }, discountTotal: { amountMinor: 0, currency: "AUD" }, total: { amountMinor: 0, currency: "AUD" } }, promotionCode: null, checkoutEligible: false, validationMessages: [] } });
    const [delivery, billing, method] = await Promise.all([this.db.address.findFirst({ where: { id: input.deliveryAddressId, customerId, type: "DELIVERY" } }), this.db.address.findFirst({ where: { id: input.billingAddressId, customerId, type: { in: ["DELIVERY", "BILLING"] } } }), this.db.deliveryMethod.findFirst({ where: { id: input.deliveryMethodId, active: true } })]);
    if (!delivery || !billing || !method) return success({ status: "CHECKOUT_CONFLICT", message: "Reload your saved addresses and delivery options." });
    if (input.promotionCode !== undefined && input.promotionCode !== (cart.promotion?.code ?? undefined)) return success({ status: "INVALID_PROMOTION", message: "The promotion changed. Review your cart before checkout." });
    const unavailable = cart.items.filter(item => item.variant.availability === "UNAVAILABLE" || !item.variant.inventory || item.variant.inventory.onHand - item.variant.inventory.reserved < item.quantity).map(item => item.variantId); if (unavailable.length) return success({ status: "OUT_OF_STOCK", variantIds: unavailable });
    const totals = money(cart); const orderId = randomUUID(); const paymentAttemptId = randomUUID(); const expiresAt = new Date(this.now().getTime() + 15 * 60 * 1000);
    try { await this.db.$transaction(async tx => { await tx.order.create({ data: { id: orderId, customerId, orderNumber: `PAL-${orderId.slice(0, 8).toUpperCase()}`, idempotencyKey: input.idempotencyKey, requestFingerprint: fingerprint(input), promotionId: cart.promotionId, deliveryMethodId: method.id, subtotalMinor: totals.subtotal, discountTotalMinor: totals.discount, deliveryChargeMinor: method.chargeMinor, totalMinor: totals.total + method.chargeMinor, currency: method.currency, deliveryAddressSnapshot: this.snapshot(delivery), billingAddressSnapshot: this.snapshot(billing), deliveryMethodSnapshot: { id: method.id, name: method.name, chargeMinor: method.chargeMinor, currency: method.currency }, items: { create: cart.items.map(item => ({ variantId: item.variantId, skuSnapshot: item.variant.sku, nameSnapshot: item.variant.perfume.name, unitPriceMinor: item.variant.priceMinor, quantity: item.quantity, personalisedLabel: item.personalisedLabel, engravingName: item.engravingName, giftMessage: item.giftMessage, giftPackagingId: item.giftPackagingId })) } } }); for (const item of cart.items) { const updated = await tx.inventoryBalance.updateMany({ where: { variantId: item.variantId, onHand: { gte: item.quantity }, reserved: { lte: (item.variant.inventory?.onHand ?? 0) - item.quantity } }, data: { reserved: { increment: item.quantity } } }); if (updated.count !== 1) throw new Error("OUT_OF_STOCK"); await tx.inventoryReservation.create({ data: { orderId, variantId: item.variantId, quantity: item.quantity, expiresAt } }); } await tx.payment.create({ data: { id: paymentAttemptId, orderId, status: "PENDING" } }); }); } catch (error) { if (error instanceof Error && error.message === "OUT_OF_STOCK") return success({ status: "OUT_OF_STOCK", variantIds: cart.items.map(item => item.variantId) }); throw error; }
    return success({ status: "READY_FOR_PAYMENT", orderId, paymentAttemptId, expiresAt: expiresAt.toISOString() });
  }
  private snapshot(address: { recipientName: string; line1: string; line2: string | null; suburb: string; state: string; postcode: string; country: string }): Record<string, string | null> { return { recipientName: address.recipientName, line1: address.line1, line2: address.line2, suburb: address.suburb, state: address.state, postcode: address.postcode, country: address.country }; }
}
export function checkoutApi(service: CheckoutService, customerId: string): CheckoutApi { return { getDeliveryMethods: () => service.getDeliveryMethods(), submit: input => service.submit(customerId, input) }; }
